### PR TITLE
Install containerd 1.1.0

### PR DESCRIPTION
**Pull request by raravena80**
@egernst 

Installing containerd, needed to run kata on k8s.

### CODE REVIEW

**Review by egernst — COMMENTED** [review]
If this script gets executed, it is assumed (based on yaml) that the node already has containerd installed, and is thusly labeled "container-runtime=containerd"

**Review by raravena80 — COMMENTED** [review]
Ah cool, do you want to put this in a separate script?

**Comment by egernst** [comment]
Well, if it ends up being necessary, it should be a reference, and ideally just a pointer to install directions from containerd (or CRIO, or any other CRI shim that supports an oci comp. runtime).  The docker file, etc, assumes a cluster is already setup with nodes that can support kata (ie, either crio or containerd)

**Review by raravena80 — COMMENTED** [review]
I pushed changes with references. Let me know if that works.

**Comment by raravena80** [comment]
Old PR, closing.

**Pull request closed without merging**
